Models/Operation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Operation
    {
        public int Id { get; set; }


        public DateTime BillDate { get; set; }


        public int BillNumber { get; set; }


        public int DeliveryReceiptNumber { get; set; }


        public string Type { get; set; }


        public string Unit { get; set; }


        public int PriceInTons { get; set; }


        public int Quantity { get; set; }


        public int Tax14 { get; set; }


        public int Tax1 { get; set; }


        public DateTime DueDate { get; set; }

        public string Creditor { get; set; }
        public string Debtor { get; set; }


        public int Subtotal { get; set; }


        public string Notes { get; set; }
    }
}

Controllers/OperationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class OperationController : Controller
    {
        private ApplicationDbContext _context;

        public OperationController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        public IEnumerable<Operation> GetOperations()
        {
            return _context.Operations.ToList();

        }
        public ActionResult AddOrEdit(int id = 0)
        {
            
            if (id != 0)
            {
                var OperationInDb = _context.Operations.SingleOrDefault(c => c.Id == id);
                return View(OperationInDb);
            }
            else
            {
                Operation operation = new Operation();
                return View(operation);
            }

            
        }
        [HttpPost]
        public ActionResult AddOrEdit(Operation operation)
        {
            try
            {

                if (operation.Id == 0)
                {
                    _context.Operations.Add(operation);
                    _context.SaveChanges();
                }
                else
                {
                    var OperationInDb = _context.Operations.SingleOrDefault(c => c.Id == operation.Id);
                    if (OperationInDb == null)
                    {
                        return Json(new { success = false, message = "Operation is not found in DB " }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        OperationInDb.Notes = operation.Notes;
                        OperationInDb.PriceInTons = operation.PriceInTons;
                        OperationInDb.Subtotal = operation.Subtotal;
                        OperationInDb.Quantity = operation.Quantity;
                        OperationInDb.DeliveryReceiptNumber = operation.DeliveryReceiptNumber;
                        OperationInDb.Tax1 = operation.Tax1;
                        OperationInDb.Tax14 = operation.Tax14;
                        OperationInDb.BillDate = operation.BillDate;
                        OperationInDb.BillNumber = operation.BillNumber;
                        OperationInDb.Creditor = operation.Creditor;
                        OperationInDb.Debtor = operation.Debtor;
                        OperationInDb.DueDate = operation.DueDate;
                        OperationInDb.Type = operation.Type;
                        OperationInDb.Unit = operation.Unit;
   
     
                        _context.SaveChanges();
                    }


                }

                return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "OperationList", GetOperations()), message = "Submitted Successfully" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult OperationList()
        {
            var OperationList = _context.Operations.ToList();
            return View(OperationList);
        }
        public ActionResult Delete(int id)
        {
            try
            {
                var OperationInDB = _context.Operations.SingleOrDefault(s => s.Id == id);
                _context.Operations.Remove(OperationInDB);
                _context.SaveChanges();

                return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "OperationList", GetOperations()), message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Views/Operation/AddOrEdit.cshtml
@model WebApplication1.Models.Operation
@{
    ViewBag.Title = "AddOrEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AddOrEdit", "Operation", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return jQueryAjaxPost(this);", data_restUrl = Url.Action("AddOrEdit", "Operation", new { id = 0 }) }))//data-resetUrl
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="form-horizontal">
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.Id)
            <br />
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.BillDate, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.BillDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BillDate)
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.BillDate, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.BillNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BillNumber)
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Creditor, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Creditor, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Creditor)
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Debtor, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Debtor, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Debtor)
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.DeliveryReceiptNumber, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DeliveryReceiptNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DeliveryReceiptNumber)
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.DueDate, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DueDate)
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Notes, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Notes)
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.PriceInTons, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PriceInTons, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PriceInTons)
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Quantity, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Quantity)
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Subtotal, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Subtotal, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Subtotal)
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Tax1, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Tax1, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Tax1)
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Tax14, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Tax14, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Tax14)
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Type, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Type)
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Unit, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Unit, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Unit)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Submit" class="btn btn-default" />
                    @if (Model.Id !=0)
                    {
                        <a class="btn btn-success" onclick="refreshAddNewTab('@Url.Action("AddOrEdit","Operation",new{id=0})',false)"><i class="fa fa-plus"></i> Add New</a>
                    }
                </div>
            </div>
        </div>
    </div>

}

Views/Operation/OperationList.cshtml
@model IEnumerable<WebApplication1.Models.Operation>
@{
    ViewBag.Title = "OperationList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>OperationList</h2>
<div class="container">
    <div class="row">
        <table id="operations" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th> ID</th>
                    <th>Bill Date</th>
                    <th>Bill Number</th>
                    <th>Delivery Receipt Number</th>
                    <th>Type</th>
                    <th>Unit</th>
                    <th>PriceInTons</th>
                    <th> Quantity</th>
                    <th>Tax in 14%</th>
                    <th> Tax in 1%</th>
                    <th>Due Date </th>
                    <th> Creditor </th>
                    <th> Debtor </th>
                    <th> Subtotal </th>
                    <th> Notes </th>
                    <th>Action</th>
                    
                </tr>
            </thead>
            <tbody>
                @foreach (var operation in Model)
                {
                    <tr>
                        <td>@operation.Id</td>
                        <td>@operation.BillDate</td>
                        <td>@operation.BillNumber</td>
                        <td>@operation.DeliveryReceiptNumber</td>
                        <td>@operation.Type</td>
                        <td>@operation.Unit</td>
                        <td>@operation.PriceInTons</td>
                        <td>@operation.Quantity</td>
                        <td>@operation.Tax14</td>
                        <td>@operation.Tax1</td>
                        <td>@operation.DueDate</td>
                        <td>@operation.Creditor</td>
                        <td>@operation.Debtor</td>
                        <td>@operation.Subtotal</td>
                        <td>@operation.Notes</td>
                        <td>
                            <a class="btn btn-primary btn-sm" onclick="Edit('@Url.Action("AddOrEdit", "Operation", new { id = operation.Id })')"><i class="fa fa-pencil fa-lg"></i></a>
                            <a class="btn btn-danger btn-sm" onclick="Delete('@Url.Action("Delete", "Operation", new { id = operation.Id })')"><i class="fa fa-trash fa-lg"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Operation/index.cshtml
@{
    ViewBag.Title = "index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ul class="nav nav-tabs">
    <li><a data-toggle="tab" href="#firstTab">View All</a></li>
    <li class="active"><a data-toggle="tab" href="#secondTab">Add New</a></li>
</ul>
<div class="tab-content">
    <div id="firstTab" class="tab-pane fade in">@Html.Action("OperationList")</div>
    <div id="secondTab" class="tab-pane fade in active">@Html.Action("AddOrEdit")</div>
</div>

<link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script>
        function activatejQueryTable() {
            $("#employeeTable").DataTable();
        }

        $(function () {
            activatejQueryTable();
        });

    </script>
}