Models/Supplier.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Supplier
    {
        public int ID { get; set; }
  
        public string Name { get; set; }


        public int SNN { get; set; }


        public string Address { get; set; }

        public byte TaxcardImage { get; set; }


        public byte RecordImage { get; set; }
    }
}

Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
namespace WebApplication1.Controllers
{
    public class SupplierController : Controller
    {
        private ApplicationDbContext _context;
        public ActionResult Index()
        {
            return View();
        }
        public SupplierController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        public IEnumerable<Supplier> GetSuppliers()
        {
            return _context.Suppliers.ToList();

        }
        public ActionResult AddOrEdit(int id = 0)
        {
           

            if (id != 0)
            {
                var SupplierInDb = _context.Suppliers.SingleOrDefault(c => c.ID == id);
                return View(SupplierInDb);
            }
            else {
                Supplier supplier = new Supplier();
                return View(supplier);
            }
                
        }
        [HttpPost]
        public ActionResult AddOrEdit(Supplier supplier)
        {
            try
            {

                if (supplier.ID == 0)
                    {
                      _context.Suppliers.Add(supplier);
                        _context.SaveChanges();
                    }
                    else
                    {
                    var SupplierInDb = _context.Suppliers.SingleOrDefault(c => c.ID == supplier.ID);
                    if (SupplierInDb == null)
                    {
                        return Json(new { success = false, message = "Supplier is not found in DB "}, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        SupplierInDb.Name = supplier.Name;
                        SupplierInDb.Address = supplier.Address;
                        SupplierInDb.RecordImage = supplier.RecordImage;
                        SupplierInDb.SNN = supplier.SNN;
                        SupplierInDb.TaxcardImage = supplier.TaxcardImage;
                        _context.SaveChanges();
                    }

                }
               
                return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "SupplierList", GetSuppliers()), message = "Submitted Successfully" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }


        public ActionResult SupplierList()
        {
            var SupplierList = _context.Suppliers.ToList();
            return View(SupplierList);
        }

        public ActionResult Delete(int id)
        {
            try
            {
                 var SupplierInDB = _context.Suppliers.SingleOrDefault(s => s.ID == id);
                _context.Suppliers.Remove(SupplierInDB);
                _context.SaveChanges();

                return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "SupplierList", GetSuppliers()), message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Views/Supplier/AddOrEdit.cshtml
@model WebApplication1.Models.Supplier
@{
    ViewBag.Title = "AddOrEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AddOrEdit", "Supplier", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return jQueryAjaxPost(this);", data_restUrl = Url.Action("AddOrEdit", "Supplier", new { id = 0 }) }))//data-resetUrl
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="form-horizontal">
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.ID)
            <br />
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.RecordImage, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.RecordImage, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RecordImage)
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.SNN, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SNN, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SNN)
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.TaxcardImage, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TaxcardImage, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TaxcardImage)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Submit" class="btn btn-default" />
                    @if (Model.ID!= 0)
                    {
                        <a class="btn btn-success" onclick="refreshAddNewTab('@Url.Action("AddOrEdit","Supplier",new{id=0})',false)"><i class="fa fa-plus"></i> Add New</a>
                    }
                </div>
            </div>
        </div>
    </div>

}

Views/Supplier/SupplierList.cshtml
@model IEnumerable<WebApplication1.Models.Supplier>
@{
    ViewBag.Title = "SupplierList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SupplierList</h2>
<div class="container">
    <div class="row">
        <table id="admins" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th> ID</th>
                    <th>Name</th>
                    <th>SNN</th>
                    <th> Address</th>
                    <th>TaxCard image</th>
                    <th>Record image</th>
                    <th>Action</th>
     
                </tr>
            </thead>
            <tbody>
                @foreach (var supplier in Model)
                {
                <tr>
                    <td>@supplier.ID</td>
                    <td>@supplier.Name</td>
                    <td>@supplier.SNN</td>
                    <td>@supplier.Address</td>
                    <td>@supplier.TaxcardImage</td>
                    <td>@supplier.RecordImage</td>
                    <td>
                        <a class="btn btn-primary btn-sm" onclick="Edit('@Url.Action("AddOrEdit", "Supplier", new { id = supplier.ID })')"><i class="fa fa-pencil fa-lg"></i></a>
                        <a class="btn btn-danger btn-sm" onclick="Delete('@Url.Action("Delete", "Supplier", new { id = supplier.ID })')"><i class="fa fa-trash fa-lg"></i></a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Supplier/index.cshtml
@{
    ViewBag.Title = "index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ul class="nav nav-tabs">
    <li><a data-toggle="tab" href="#firstTab">View All</a></li>
    <li class="active"><a data-toggle="tab" href="#secondTab">Add New</a></li>
</ul>
<div class="tab-content">
    <div id="firstTab" class="tab-pane fade in">@Html.Action("SupplierList")</div>
    <div id="secondTab" class="tab-pane fade in active">@Html.Action("AddOrEdit")</div>
</div>

<link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script>
        function activatejQueryTable() {
            $("#employeeTable").DataTable();
        }

        $(function () {
            activatejQueryTable();
        });

    </script>
}